import os
import cv2
import re
import numpy as np
from tensorflow.lite.python.interpreter import Interpreter
import time
import base64
from flask import Flask, request, render_template, send_file
from io import BytesIO
from PIL import Image
from dotenv import load_dotenv

#  Hugging Face 
from huggingface_hub import InferenceClient

app = Flask(__name__)

from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

latest_result = {}

@app.route('/download_report')
def download_report():
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.lib.units import inch

    REPORT_FOLDER = os.path.join('static', 'reports')
    os.makedirs(REPORT_FOLDER, exist_ok=True)

    file_path = os.path.join(REPORT_FOLDER, 'report.pdf')

    #  Save image temporarily
    image_path = os.path.join(REPORT_FOLDER, 'plant.jpg')

    # Decode base64 image (latest uploaded image)
    if latest_result.get("image"):
        with open(image_path, "wb") as f:
            f.write(base64.b64decode(latest_result["image"]))

    # Create PDF
    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()

    content = []

    # 🔹 Title
    content.append(Paragraph("🌿 Plant Disease Detection Report", styles['Title']))
    content.append(Spacer(1, 20))

    # 🔹 Image
    if os.path.exists(image_path):
        img = Image(image_path, width=4*inch, height=3*inch)
        content.append(img)
        content.append(Spacer(1, 20))

    # 🔹 Details
    content.append(Paragraph("<b>Disease:</b> " + latest_result.get("disease", "N/A"), styles['Normal']))
    content.append(Spacer(1, 10))

    content.append(Paragraph("<b>Confidence:</b> " + latest_result.get("confidence", "N/A"), styles['Normal']))
    content.append(Spacer(1, 15))

    content.append(Paragraph("<b>Treatment:</b>", styles['Heading2']))
    content.append(Spacer(1, 10))

    content.append(Paragraph(latest_result.get("treatment", "N/A"), styles['Normal']))

    content.append(Spacer(1, 20))

    content.append(Paragraph("✔ Generated by Plant Disease Detection System", styles['Italic']))

    # Build PDF
    doc.build(content)

    return send_file(file_path, as_attachment=True)

# ==============================
# 🔹 HUGGING FACE CONFIG
# ==============================

load_dotenv()
HF_TOKEN = os.getenv("HF_TOKEN")

client = InferenceClient(
    model="HuggingFaceH4/zephyr-7b-beta",
    token=HF_TOKEN
)

cache = {}
import time
last_api_call = 0

# ==============================
# 🔹 LOAD MODEL
# ==============================
interpreter = Interpreter(model_path="./model/PlantX_model.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print("✅ TFLite Model Loaded Successfully!")

class_names = [
    "Pepper__bell___Bacterial_spot",
    "Pepper__bell___healthy",
    "Potato___Early_blight",
    "Potato___Late_blight",
    "Potato___healthy",
    "Tomato_Bacterial_spot",
    "Tomato_Early_blight",
    "Tomato_Late_blight",
    "Tomato_Leaf_Mold",
    "Tomato_Septoria_leaf_spot",
    "Tomato_Spider_mites_Two_spotted_spider_mite",
    "Tomato__Target_Spot",
    "Tomato__Tomato_YellowLeaf__Curl_Virus",
    "Tomato__Tomato_mosaic_virus",
    "Tomato_healthy"
]

# ==============================
# 🔹 IMAGE PROCESSING
# ==============================
def preprocess_image(image_bytes, target_size=(224, 224)):
    image = Image.open(BytesIO(image_bytes)).convert("RGB")
    image = image.resize(target_size)
    image = np.array(image, dtype=np.float32) / 255.0
    return image

def encode_image(image_bytes):
    return base64.b64encode(image_bytes).decode('utf-8')

# ==============================
# 🔹 TEXT PROCESSING
# ==============================
def extract_info(text, keyword):
    # Allow variations like Treatment, Treatments, Management
    keywords_map = {
        "Disease Description": ["Disease Description"],
        "Cause": ["Cause", "Causes"],
        "Treatment": ["Treatment", "Treatments", "Management", "Prevention"]
    }

    for key in keywords_map.get(keyword, [keyword]):
        pattern = rf"{key}\s*[:\-]\s*(.*?)(?=\n[A-Za-z ]+\s*[:\-]|$)"
        match = re.search(pattern, text, re.DOTALL | re.IGNORECASE)

        if match:
            return match.group(1).strip()

    return "Info not available."

# ==============================
# 🔹 HUGGING FACE FUNCTION
# ==============================
def get_disease_info(disease_name):

    import re

    disease_name = disease_name.replace("__", " ").replace("_", " ")
    disease_name = re.sub(r'\s+', ' ', disease_name).strip()

    if disease_name in cache:
        print("✅ From cache:", disease_name)
        return cache[disease_name]
    
    # 🔹 Rate limit control (ADD HERE)
    global last_api_call
    if time.time() - last_api_call < 1:
        time.sleep(1)
    last_api_call = time.time()

    prompt = f"""
You are an expert plant pathologist.

Give COMPLETE and structured information about {disease_name}.

IMPORTANT:
You MUST include ALL 3 sections.

Format strictly like this:

Disease Description:
Write 2-3 lines.

Cause:
Write 2-3 points.

Treatment:
Write 3-4 points.

DO NOT skip any section.
"""

    try:
        response = client.chat_completion(
            messages=[
                {"role": "user", "content": prompt}
            ],
            max_tokens=1000,
            temperature=0.5
        )

        text = response.choices[0].message.content
        print("=== FULL AI RESPONSE ===")
        print(text)
        print("========================")

        disease_info = extract_info(text, "Disease Description")
        cause = extract_info(text, "Cause")
        treatment = extract_info(text, "Treatment")

        # Smart fallback for missing sections
        if "Info not available" in cause:
            cause = "This disease is mainly caused by viral, fungal, or bacterial infection affecting plant growth."

        if "Info not available" in treatment:
            treatment = """1. Remove infected leaves
            2. Use recommended pesticides
            3. Control insects like whiteflies
            4. Maintain proper field hygiene"""

    except Exception as e:
        print("❌ HF Error:", e)
        return fallback_data()

    cache[disease_name] = (disease_info, cause, treatment)

    return disease_info, cause, treatment

# ==============================
# 🔹 FALLBACK
# ==============================
def fallback_data():
    return (
        "This disease affects plant health and reduces crop productivity.",
        "Caused by fungal, bacterial, or environmental factors.",
        "Use proper pesticides, remove infected leaves, and maintain hygiene."
    )

# ==============================
# 🔹 PREDICTION
# ==============================
def predict_single_image(image_bytes):
    image = preprocess_image(image_bytes)

    image_expanded = np.expand_dims(image, axis=0).astype(np.float32)
    interpreter.set_tensor(input_details[0]['index'], image_expanded)

    start_time = time.time()
    interpreter.invoke()
    end_time = time.time()

    output_data = interpreter.get_tensor(output_details[0]['index'])
    predicted_index = np.argmax(output_data)
    predicted_class = class_names[predicted_index]
    confidence_score = output_data[0][predicted_index] * 100
    prediction_time = end_time - start_time

    print("Predicted:", predicted_class)
    clean_name = predicted_class.replace("_", " ")

    disease_info, cause, treatment = get_disease_info(clean_name)
    return predicted_class, confidence_score, prediction_time, disease_info, cause, treatment

# ==============================
# 🔹 ROUTES
# ==============================
app.config["MAX_CONTENT_LENGTH"] = 12 * 1024 * 1024

@app.route("/", methods=["GET", "POST"])
def upload_file():
    if request.method == "POST":
        files = request.files.getlist("files")

        if not files or all(file.filename == "" for file in files):
            return render_template("upload.html", error="No files selected!")

        new_results = []

        for file in files:
            image_bytes = file.read()
            encoded_image = encode_image(image_bytes)

            predicted_class, confidence, time_taken, disease_info, cause, treatment = predict_single_image(image_bytes)

            global latest_result

            latest_result = {
                "disease": predicted_class,
                "confidence": f"{confidence:.2f}%",
                "treatment": treatment,
                "image": encoded_image
            }

            new_results.append({
                "image": encoded_image,
                "disease": predicted_class,
                "confidence": f"{confidence:.2f}%",
                "time_taken": f"{time_taken:.4f} sec",
                "disease_info": disease_info,
                "cause": cause,
                "treatment": treatment
            })

        return render_template("result.html", results=new_results)

    return render_template("upload.html")

# ==============================
# 🔹 RUN
# ==============================
if __name__ == "__main__":
    app.run(debug=True)